### ISSUE TITLE
use WP_Http to make request

### ISSUE THREAD

**Issue by columbian-chris** [maneuver-agency/bitbucket-wp-updater#1]
This package is extremely helpful; thank you so much!

I have one suggestion: can we use the `WP_Http` class to make the request in the `makeRequest` method instead of just straight cURL so that the request can be tracked via Query Monitor (or similar debug tools)?

You could essentially replace everything in the method with simply `return wp_remote_retrieve_body(wp_remote_get($url));`.

**Comment by columbian-chris** [comment]
You could essentially replace everything in the method with simply `return wp_remote_retrieve_body(wp_remote_get($url));`.

**Comment by davidmaneuver** [comment]
Hi @columbian-chris, thank you.

As we are not using Wordpress anymore, this package is unfortunately unmaintained.

gr.

**Comment by columbian-chris** [comment]
@davidmaneuver Thank you!
